Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-ml"

  # Port forwarding
  config.vm.network "forwarded_port", guest: 5000, host: 5001, auto_correct: true

  # Public network (LAN IP)
  config.vm.network "public_network", bridge: "wlp0s20f3" # Replace with correct interface

  # Synced folder
  config.vm.synced_folder "/exports", "/exports", create: true

  # VM Resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
end

